<?php

namespace App\Exceptions;

use Bestdecoders\ShopifyLaravelEnhanced\Traits\HandlesShopifyExceptions;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

/**
 * Enhanced Exception Handler with Shopify-specific exception handling
 * 
 * This handler automatically handles common Shopify authentication exceptions
 * and provides user-friendly responses for direct access to install routes.
 * 
 * Generated by Shopify Laravel Enhanced package.
 */
class Handler extends ExceptionHandler
{
    use HandlesShopifyExceptions;

    /**
     * A list of exception types with their corresponding custom log levels.
     *
     * @var array<class-string<\Throwable>, \Psr\Log\LogLevel::*>
     */
    protected $levels = [
        //
    ];

    /**
     * A list of the exception types that are not reported.
     *
     * @var array<int, class-string<\Throwable>>
     */
    protected $dontReport = [
        // Shopify exceptions are automatically added by HandlesShopifyExceptions trait
    ];

    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        // Automatically merge Shopify exceptions into dontReport array
        // This prevents "No authenticated user or shop domain" from cluttering logs
        $this->mergeShopifyDontReport();

        $this->reportable(function (Throwable $e) {
            // Add your custom exception reporting logic here
        });
    }

    /**
     * Render an exception into an HTTP response.
     */
    public function render($request, Throwable $exception)
    {
        // Handle Shopify-specific exceptions first
        // This provides user-friendly responses for authentication issues
        $shopifyResponse = $this->renderShopifyException($request, $exception);
        if ($shopifyResponse !== null) {
            return $shopifyResponse;
        }

        // Add your custom exception rendering logic here
        
        // Fall back to Laravel's default exception handling
        return parent::render($request, $exception);
    }
}